$my_base_url                     = "https://rally1.rallydev.com/slm"
$my_username                     = "user@company.com"
$my_password                     = "topsecret"
$my_workspace                    = "My Workspace"
$my_project                      = "My Project"
$wsapi_version                   = "1.40"
$filename                        = "copy_test_cases.csv"